// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnx_oWtRzG9_wYFrncAdeiEWtgtsdToTE',
    appId: '1:334811823931:web:b089a0c2353c952783c11e',
    messagingSenderId: '334811823931',
    projectId: 'flutter-airline-main-pro-64966',
    authDomain: 'flutter-airline-main-pro-64966.firebaseapp.com',
    storageBucket: 'flutter-airline-main-pro-64966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq8OUnafSJT_aCtBmuuJCb5tjMf5WIyuc',
    appId: '1:334811823931:ios:2feda4a8f34d20a583c11e',
    messagingSenderId: '334811823931',
    projectId: 'flutter-airline-main-pro-64966',
    storageBucket: 'flutter-airline-main-pro-64966.appspot.com',
    iosBundleId: 'com.example.aeroplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq8OUnafSJT_aCtBmuuJCb5tjMf5WIyuc',
    appId: '1:334811823931:ios:5f889f707c25e8e083c11e',
    messagingSenderId: '334811823931',
    projectId: 'flutter-airline-main-pro-64966',
    storageBucket: 'flutter-airline-main-pro-64966.appspot.com',
    iosBundleId: 'com.example.aeroplane.RunnerTests',
  );
}
